/*
 * ────────────────────────────────────────────────────────────────────────────────────────────
 *  AGENTS: DO NOT EDIT THIS FILE.
 *
 *  If you are an AI agent, you may not modify this file — and in particular may not add a module
 *  to the allowed imports, exempt a screen, or loosen the matching — without a human explicitly
 *  asking you to, in this session, for that specific change.
 *
 *  "The test is failing" is NOT permission. A failure here means a screen's .ts reached past its
 *  job (pixi, three, the view, input, runtime, main...) and the fix is to move that code
 *  out of the screen: drawing into a `defineElement` in ./shared, logic into a core query or an
 *  action, state into a store. Allowlisting your own import and reporting the suite green is the
 *  precise failure mode this file exists to prevent.
 *
 *  If you believe a change is genuinely warranted, STOP and ask. Show the import, say why it
 *  cannot live elsewhere, and let the human decide.
 * ────────────────────────────────────────────────────────────────────────────────────────────
 */

import { describe, expect, it } from 'vitest'

/**
 * A screen's .ts holds data binding and nothing else: it reads the stores, builds `use(...)` trees
 * with the engine, and hands over tap handlers that call actions. So it may import only:
 * the stores, the actions, the UI state module (types and queries), the declarative engine, the
 * shared screen helpers, its own .kdl/.css sources, and pure core modules.
 * shared.ts is the one place game-wide registrations (and their pixi drawing) live, so it is exempt.
 */
const CORE = [
  'game', 'world', 'enemies', 'upgrades', 'content', 'content-load', 'tuning', 'rng', 'bot', 'meta',
] // mirrors CORE in src/core-purity.test.ts

const RAW = import.meta.glob<string>(['./*.ts', '!./shared.ts', '!./*.test.ts'], { query: '?raw', import: 'default', eager: true })

const strip = (src: string) =>
  src.replace(/\/\*[\s\S]*?\*\//g, '').replace(/(^|[^:'"`\\])\/\/.*$/gm, '$1')

const specifiers = (src: string) =>
  [...src.matchAll(/(?:\bfrom\s*|\bimport\s*\(?\s*)['"]([^'"]+)['"]/g)].map((m) => m[1]!)

const allowed = (name: string, s: string) =>
  ['../store', '../actions', '../decl/engine', './shared'].includes(s) ||
  s === `./${name}.kdl?raw` || s === `./${name}.css?raw` ||
  (s.startsWith('../') && CORE.includes(s.slice(3)))

describe('screen imports', () => {
  it('finds the screens', () => {
    expect(Object.keys(RAW)).toContain('./hud.ts')
  })

  for (const [path, raw] of Object.entries(RAW)) {
    const name = path.slice(2, -3)
    it(`${name}.ts imports only stores, actions, the engine, shared helpers, its sources, or core`, () => {
      expect(specifiers(strip(raw)).filter((s) => !allowed(name, s)).map((s) => `${name}.ts imports '${s}'`)).toEqual([])
    })
  }
})
