/*
 * ────────────────────────────────────────────────────────────────────────────────────────────
 *  AGENTS: DO NOT EDIT THIS FILE.
 *
 *  If you are an AI agent, you may not modify this file — and in particular may not add a module
 *  to the allowed imports, remove a module from `CORE`, or loosen `FORBIDDEN_APIS` — without a
 *  human explicitly asking you to, in this session, for that specific change.
 *
 *  "The test is failing" is NOT permission. A failure here means core code reached for the shell
 *  (pixi, zustand, the DOM, localStorage, the store, actions, main, screens...) and the fix is to
 *  move that code to the shell, not to widen a list. Allowlisting your own import and reporting
 *  the suite green is the precise failure mode this file exists to prevent.
 *
 *  If you believe a change is genuinely warranted, STOP and ask. Show the import or API, say why
 *  it cannot live in the shell, and let the human decide.
 * ────────────────────────────────────────────────────────────────────────────────────────────
 */


import { describe, expect, it } from 'vitest'

/**
 * Functional core / imperative shell. The core is (state, action) -> state: pure functions over
 * plain data, so it runs headless in tests and in the sim with no renderer, store, DOM or storage.
 * Everything effectful (pixi, zustand, audio, clock, persistence, screens) lives in the shell
 * (store / actions / runtime / main / screens / view) and calls into the core, never the other way round.
 *
 * Rule 1: a core module may import only zod, kdljs, KDL content files, or another core module (so no pixi, three, zustand).
 * Rule 2: a core module may not reference browser or environment APIs.
 */
const CORE = [
  'game', 'world', 'enemies', 'upgrades', 'content', 'content-load', 'tuning', 'rng', 'bot', 'meta',
]

const FORBIDDEN_APIS = [
  'localStorage', 'sessionStorage', 'document', 'window', 'navigator', 'requestAnimationFrame',
  'indexedDB', 'import\\.meta\\.env',
]

const RAW = import.meta.glob<string>('./*.ts', { query: '?raw', import: 'default', eager: true })

const strip = (src: string) =>
  src.replace(/\/\*[\s\S]*?\*\//g, '').replace(/(^|[^:'"`\\])\/\/.*$/gm, '$1')

const specifiers = (src: string) =>
  [...src.matchAll(/(?:\bfrom\s*|\bimport\s*\(?\s*)['"]([^'"]+)['"]/g)].map((m) => m[1]!)

const allowed = (s: string) =>
  s === 'zod' || s === 'kdljs' || /^\.\.\/content\/[\w.-]+\.kdl\?raw$/.test(s) ||
  (s.startsWith('./') && CORE.includes(s.slice(2)))

describe('core purity', () => {
  for (const name of CORE) {
    const src = strip(RAW[`./${name}.ts`] ?? '')

    it(`${name}.ts exists`, () => {
      expect(RAW[`./${name}.ts`], `${name}.ts is listed in CORE but missing`).toBeDefined()
    })

    it(`${name}.ts imports only zod, kdljs, content kdl, or core modules`, () => {
      expect(specifiers(src).filter((s) => !allowed(s)).map((s) => `${name}.ts imports '${s}'`)).toEqual([])
    })

    it(`${name}.ts references no browser or environment APIs`, () => {
      const hits = FORBIDDEN_APIS.filter((t) => new RegExp(`\\b${t}\\b`).test(src))
      expect(hits.map((t) => `${name}.ts references ${t.replace('\\', '')}`)).toEqual([])
    })
  }
})
